# ============================================================
# Classifier 4 — CNN on MFCC Spectrograms (EfficientNet-B0)
# Acoustic Impact Hammer Testing: Cracked vs Intact
#
# Loads MFCC_Images/ (generated by MFCC_Image_Generator.py),
# extracts deep features from pretrained EfficientNet-B0,
# then trains a lightweight classifier head on those features.
#
# This "feature extraction" approach runs the heavy backbone
# only once, then trains the head in seconds — making it
# practical on CPU while still leveraging the full pretrained
# convolutional representations.
#
# Output: Classifier Results/CNN_MFCC/
# ============================================================

import os
import json
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torchvision import datasets, transforms, models
from torchvision.models import EfficientNet_B0_Weights

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report
)
from tqdm import tqdm


# ============================================================
# PARAMETERS
# ============================================================

IMAGE_DIR      = "MFCC_Images"
OUTPUT_DIR     = os.path.join("Classifier Results", "CrackDetection", "CNN_MFCC")
RANDOM_STATE   = 42

EXTRACT_BATCH  = 64       # batch size for one-time feature extraction
TRAIN_BATCH    = 256      # batch size for head training (features fit in RAM)
EPOCHS         = 50       # head training epochs (very fast — features are cached)
LR             = 1e-3
WEIGHT_DECAY   = 1e-4

# ImageNet normalisation — required for pretrained EfficientNet weights
IMAGENET_MEAN  = [0.485, 0.456, 0.406]
IMAGENET_STD   = [0.229, 0.224, 0.225]

os.makedirs(OUTPUT_DIR, exist_ok=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")


# ============================================================
# STEP 1 — Load dataset, build labels
# ImageFolder maps alphabetically: Cracked=0, Intact=1
# ============================================================

print("\nLoading dataset paths...")

img_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

full_dataset = datasets.ImageFolder(IMAGE_DIR, transform=img_transforms)
class_names  = full_dataset.classes          # ['Cracked', 'Intact']
targets      = np.array(full_dataset.targets)

print(f"  Total images : {len(targets)}")
print(f"  Cracked (0)  : {(targets == 0).sum()}")
print(f"  Intact  (1)  : {(targets == 1).sum()}")


# ============================================================
# STEP 2 — Load pretrained EfficientNet-B0, strip classifier
# We use it purely as a fixed feature extractor
# ============================================================

print("\nLoading EfficientNet-B0 backbone...")
backbone = models.efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)

# Remove the classifier head — keep only the feature extractor
backbone.classifier = nn.Identity()

# Freeze everything — backbone is never updated
for param in backbone.parameters():
    param.requires_grad = False

backbone = backbone.to(device)
backbone.eval()

total_params = sum(p.numel() for p in backbone.parameters())
print(f"  Backbone params (frozen): {total_params:,}")


# ============================================================
# STEP 3 — Extract features for all images (one-time pass)
# Produces an (N, 1280) feature matrix for the full dataset
# ============================================================

print(f"\nExtracting features ({len(full_dataset)} images)...")
print("  (This runs the backbone once — subsequent training is fast)")

loader = DataLoader(full_dataset, batch_size=EXTRACT_BATCH,
                    shuffle=False, num_workers=0)

all_features = []
all_labels   = []

with torch.no_grad():
    for images, labels in tqdm(loader, desc="Extracting", unit="batch"):
        images = images.to(device)
        feats  = backbone(images)                  # (B, 1280)
        all_features.append(feats.cpu())
        all_labels.append(labels)

features = torch.cat(all_features, dim=0)          # (N, 1280)
labels   = torch.cat(all_labels,   dim=0)          # (N,)

print(f"  Feature matrix: {features.shape}")


# ============================================================
# STEP 4 — Train / val / test splits (stratified)
# ============================================================

all_idx = np.arange(len(labels))
y_np    = labels.numpy()

trainval_idx, test_idx = train_test_split(
    all_idx, test_size=0.2, stratify=y_np, random_state=RANDOM_STATE
)
train_idx, val_idx = train_test_split(
    trainval_idx, test_size=0.1,
    stratify=y_np[trainval_idx], random_state=RANDOM_STATE
)

print(f"\n  Train: {len(train_idx)}  |  Val: {len(val_idx)}  |  Test: {len(test_idx)}")

X_train = features[train_idx];  y_train = labels[train_idx]
X_val   = features[val_idx];    y_val   = labels[val_idx]
X_test  = features[test_idx];   y_test  = labels[test_idx]

train_loader = DataLoader(TensorDataset(X_train, y_train),
                          batch_size=TRAIN_BATCH, shuffle=True)
val_loader   = DataLoader(TensorDataset(X_val,   y_val),
                          batch_size=TRAIN_BATCH, shuffle=False)
test_loader  = DataLoader(TensorDataset(X_test,  y_test),
                          batch_size=TRAIN_BATCH, shuffle=False)


# ============================================================
# STEP 5 — Build classifier head
# Input: 1280-dim EfficientNet-B0 features
# Output: 2-class logits
# ============================================================

head = nn.Sequential(
    nn.Linear(1280, 256),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(256, 2)
).to(device)

print(f"\n  Head params: {sum(p.numel() for p in head.parameters()):,}")


# ============================================================
# CLASS WEIGHTS for imbalance (Cracked is minority)
# ============================================================

n_cracked      = int((y_np == 0).sum())
n_intact       = int((y_np == 1).sum())
weight_cracked = len(y_np) / (2 * n_cracked)
weight_intact  = len(y_np) / (2 * n_intact)
class_weights  = torch.tensor([weight_cracked, weight_intact],
                               dtype=torch.float32).to(device)

print(f"  Class weights — Cracked: {weight_cracked:.3f}  |  Intact: {weight_intact:.3f}")


# ============================================================
# STEP 6 — Train the head
# ============================================================

criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(head.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", patience=5, factor=0.5
)


def run_epoch(head, loader, optimizer=None):
    training = optimizer is not None
    head.train() if training else head.eval()

    total_loss = 0.0
    all_preds  = []
    all_labels = []

    ctx = torch.enable_grad() if training else torch.no_grad()
    with ctx:
        for feats, lbls in loader:
            feats, lbls = feats.to(device), lbls.to(device)

            if training:
                optimizer.zero_grad()

            out  = head(feats)
            loss = criterion(out, lbls)

            if training:
                loss.backward()
                optimizer.step()

            total_loss += loss.item() * feats.size(0)
            preds = out.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(lbls.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    return avg_loss, np.array(all_preds), np.array(all_labels)


def compute_metrics(preds, labels):
    return {
        "acc":  accuracy_score(labels, preds),
        "prec": precision_score(labels, preds, pos_label=0, zero_division=0),
        "rec":  recall_score(labels, preds, pos_label=0, zero_division=0),
        "f1":   f1_score(labels, preds, pos_label=0, zero_division=0),
    }


print(f"\n{'='*55}")
print(f"Training classifier head ({EPOCHS} epochs)")
print(f"{'='*55}")

history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}
best_val_f1      = 0.0
best_val_metrics = {}

for epoch in range(1, EPOCHS + 1):
    train_loss, train_preds, train_labels = run_epoch(head, train_loader, optimizer)
    val_loss,   val_preds,   val_labels   = run_epoch(head, val_loader)

    train_m = compute_metrics(train_preds, train_labels)
    val_m   = compute_metrics(val_preds,   val_labels)

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["train_acc"].append(train_m["acc"])
    history["val_acc"].append(val_m["acc"])

    scheduler.step(val_loss)

    if val_m["f1"] > best_val_f1:
        best_val_f1      = val_m["f1"]
        best_val_metrics = val_m
        torch.save(head.state_dict(), os.path.join(OUTPUT_DIR, "best_head.pt"))

    if epoch % 5 == 0 or epoch == 1:
        print(
            f"  Epoch {epoch:3d}/{EPOCHS} | "
            f"Train Loss: {train_loss:.4f}  Acc: {train_m['acc']:.4f} | "
            f"Val Loss: {val_loss:.4f}  Acc: {val_m['acc']:.4f}  F1: {val_m['f1']:.4f}"
        )


# ============================================================
# STEP 7 — Final evaluation on test set
# ============================================================

print("\nEvaluating best model on test set...")
head.load_state_dict(torch.load(os.path.join(OUTPUT_DIR, "best_head.pt"),
                                map_location=device))

_, test_preds, test_labels = run_epoch(head, test_loader)
test_m = compute_metrics(test_preds, test_labels)
cm     = confusion_matrix(test_labels, test_preds)

print(f"\n  Accuracy : {test_m['acc']:.4f}")
print(f"  Precision: {test_m['prec']:.4f}  (Cracked)")
print(f"  Recall   : {test_m['rec']:.4f}  (Cracked)")
print(f"  F1       : {test_m['f1']:.4f}  (Cracked)")
print(f"\n{classification_report(test_labels, test_preds, target_names=class_names)}")


# ============================================================
# SAVE METRICS JSON (compatible with Classifier_Comparison.py)
# cv_* fields = best validation metrics across all epochs
# ============================================================

results = {
    "model":          "CNN_MFCC",
    "test_accuracy":  test_m["acc"],
    "test_precision": test_m["prec"],
    "test_recall":    test_m["rec"],
    "test_f1":        test_m["f1"],
    "cv_accuracy":    best_val_metrics.get("acc",  0.0),
    "cv_precision":   best_val_metrics.get("prec", 0.0),
    "cv_recall":      best_val_metrics.get("rec",  0.0),
    "cv_f1":          best_val_metrics.get("f1",   0.0),
}

with open(os.path.join(OUTPUT_DIR, "metrics.json"), "w") as f:
    json.dump(results, f, indent=2)
print("\nSaved: metrics.json")


# ============================================================
# PLOT 1 — Confusion Matrix
# ============================================================

fig, ax = plt.subplots(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=class_names, yticklabels=class_names, ax=ax)
ax.set_xlabel("Predicted")
ax.set_ylabel("Actual")
ax.set_title("CNN (EfficientNet-B0) — Confusion Matrix")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix.png"), dpi=150)
plt.close()
print("Saved: confusion_matrix.png")


# ============================================================
# PLOT 2 — Training Curves (loss + accuracy)
# ============================================================

epoch_axis = list(range(1, EPOCHS + 1))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))

ax1.plot(epoch_axis, history["train_loss"], label="Train", color="steelblue")
ax1.plot(epoch_axis, history["val_loss"],   label="Val",   color="darkorange")
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Loss")
ax1.set_title("CNN (EfficientNet-B0) — Loss")
ax1.legend()

ax2.plot(epoch_axis, history["train_acc"], label="Train", color="steelblue")
ax2.plot(epoch_axis, history["val_acc"],   label="Val",   color="darkorange")
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Accuracy")
ax2.set_title("CNN (EfficientNet-B0) — Accuracy")
ax2.set_ylim(0, 1.05)
ax2.legend()

plt.suptitle(
    "EfficientNet-B0 Feature Extraction + MLP Head Training Curves",
    fontsize=10, y=1.01
)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "training_curves.png"), dpi=150, bbox_inches="tight")
plt.close()
print("Saved: training_curves.png")


# ============================================================
# SUMMARY
# ============================================================

print(f"\n{'='*55}")
print(f"All results saved to: {OUTPUT_DIR}/")
print(f"{'='*55}")
